# Site settings
title: Jordy Cuan
header-img: img/home-bg.jpg
#email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "https://jordycr.github.io"
url: "https://jordycr.github.io"
twitter_username: JordyCRPetrucci
github_username:  jordycr
google_plus_username:  JordyCuanPetrucci

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

## ???
analytics :
  provider : google
  google:
    tracking_id : 'UA-72258304-1'
  getclicky :
    site_id